// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uber/cadence/api/v1/semaphore.proto

package apiv1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Semaphore is a named, domain-scoped limit on how many workflows may hold a token at once.
type Semaphore struct {
	SemaphoreName string `protobuf:"bytes,1,opt,name=semaphore_name,json=semaphoreName,proto3" json:"semaphore_name,omitempty"`
	// Total number of tokens.
	Size_ int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Number of tokens in each bucket. Tokens are split into buckets, and each bucket is served
	// by one host.
	BucketSize           int32    `protobuf:"varint,3,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Semaphore) Reset()         { *m = Semaphore{} }
func (m *Semaphore) String() string { return proto.CompactTextString(m) }
func (*Semaphore) ProtoMessage()    {}
func (*Semaphore) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fa81a8a38dce780, []int{0}
}
func (m *Semaphore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Semaphore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Semaphore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Semaphore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Semaphore.Merge(m, src)
}
func (m *Semaphore) XXX_Size() int {
	return m.Size()
}
func (m *Semaphore) XXX_DiscardUnknown() {
	xxx_messageInfo_Semaphore.DiscardUnknown(m)
}

var xxx_messageInfo_Semaphore proto.InternalMessageInfo

func (m *Semaphore) GetSemaphoreName() string {
	if m != nil {
		return m.SemaphoreName
	}
	return ""
}

func (m *Semaphore) GetSize_() int32 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *Semaphore) GetBucketSize() int32 {
	if m != nil {
		return m.BucketSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Semaphore)(nil), "uber.cadence.api.v1.Semaphore")
}

func init() {
	proto.RegisterFile("uber/cadence/api/v1/semaphore.proto", fileDescriptor_4fa81a8a38dce780)
}

var fileDescriptor_4fa81a8a38dce780 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x4d, 0x4a, 0x2d,
	0xd2, 0x4f, 0x4e, 0x4c, 0x49, 0xcd, 0x4b, 0x4e, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0xd4,
	0x2f, 0x4e, 0xcd, 0x4d, 0x2c, 0xc8, 0xc8, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x12, 0x06, 0x29, 0xd2, 0x83, 0x2a, 0xd2, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0x54, 0x4a, 0xe7,
	0xe2, 0x0c, 0x86, 0xa9, 0x13, 0x52, 0xe5, 0xe2, 0x83, 0x6b, 0x8a, 0xcf, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x85, 0x8b, 0xfa, 0x25, 0xe6, 0xa6, 0x0a, 0x09, 0x71,
	0xb1, 0x14, 0x67, 0x56, 0xa5, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0xf2,
	0x5c, 0xdc, 0x49, 0xa5, 0xc9, 0xd9, 0xa9, 0x25, 0xf1, 0x60, 0x29, 0x66, 0xb0, 0x14, 0x17, 0x44,
	0x28, 0x38, 0xb3, 0x2a, 0xd5, 0x29, 0xeb, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f,
	0x3c, 0x92, 0x63, 0xe4, 0x12, 0x4f, 0xce, 0xcf, 0xd5, 0xc3, 0xe2, 0x1e, 0x27, 0x3e, 0xb8, 0x6b,
	0x02, 0x40, 0x8e, 0x0e, 0x60, 0x8c, 0x32, 0x4c, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce,
	0xcf, 0xd5, 0x47, 0xf6, 0xa6, 0x6e, 0x66, 0x4a, 0x8e, 0x7e, 0x7a, 0xbe, 0x3e, 0xd8, 0x73, 0x50,
	0x3f, 0x5b, 0x27, 0x16, 0x64, 0x96, 0x19, 0x26, 0xb1, 0x81, 0xc5, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x78, 0x61, 0xf7, 0x8a, 0x17, 0x01, 0x00, 0x00,
}

func (m *Semaphore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Semaphore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Semaphore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.BucketSize != 0 {
		i = encodeVarintSemaphore(dAtA, i, uint64(m.BucketSize))
		i--
		dAtA[i] = 0x18
	}
	if m.Size_ != 0 {
		i = encodeVarintSemaphore(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SemaphoreName) > 0 {
		i -= len(m.SemaphoreName)
		copy(dAtA[i:], m.SemaphoreName)
		i = encodeVarintSemaphore(dAtA, i, uint64(len(m.SemaphoreName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSemaphore(dAtA []byte, offset int, v uint64) int {
	offset -= sovSemaphore(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Semaphore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SemaphoreName)
	if l > 0 {
		n += 1 + l + sovSemaphore(uint64(l))
	}
	if m.Size_ != 0 {
		n += 1 + sovSemaphore(uint64(m.Size_))
	}
	if m.BucketSize != 0 {
		n += 1 + sovSemaphore(uint64(m.BucketSize))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSemaphore(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSemaphore(x uint64) (n int) {
	return sovSemaphore(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Semaphore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSemaphore
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Semaphore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Semaphore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SemaphoreName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSemaphore
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSemaphore
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SemaphoreName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketSize", wireType)
			}
			m.BucketSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSemaphore
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BucketSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSemaphore(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSemaphore
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSemaphore(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSemaphore
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSemaphore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSemaphore
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSemaphore
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSemaphore
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSemaphore
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSemaphore        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSemaphore          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSemaphore = fmt.Errorf("proto: unexpected end of group")
)
