// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/api/v1/service_semaphore.proto

package apiv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// SemaphoreAPIYARPCClient is the YARPC client-side interface for the SemaphoreAPI service.
type SemaphoreAPIYARPCClient interface {
	CreateSemaphore(context.Context, *CreateSemaphoreRequest, ...yarpc.CallOption) (*CreateSemaphoreResponse, error)
}

func newSemaphoreAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) SemaphoreAPIYARPCClient {
	return &_SemaphoreAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.api.v1.SemaphoreAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewSemaphoreAPIYARPCClient builds a new YARPC client for the SemaphoreAPI service.
func NewSemaphoreAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) SemaphoreAPIYARPCClient {
	return newSemaphoreAPIYARPCClient(clientConfig, nil, options...)
}

// SemaphoreAPIYARPCServer is the YARPC server-side interface for the SemaphoreAPI service.
type SemaphoreAPIYARPCServer interface {
	CreateSemaphore(context.Context, *CreateSemaphoreRequest) (*CreateSemaphoreResponse, error)
}

type buildSemaphoreAPIYARPCProceduresParams struct {
	Server      SemaphoreAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildSemaphoreAPIYARPCProcedures(params buildSemaphoreAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_SemaphoreAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.api.v1.SemaphoreAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "CreateSemaphore",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.CreateSemaphore,
							NewRequest:  newSemaphoreAPIServiceCreateSemaphoreYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildSemaphoreAPIYARPCProcedures prepares an implementation of the SemaphoreAPI service for YARPC registration.
func BuildSemaphoreAPIYARPCProcedures(server SemaphoreAPIYARPCServer) []transport.Procedure {
	return buildSemaphoreAPIYARPCProcedures(buildSemaphoreAPIYARPCProceduresParams{Server: server})
}

// FxSemaphoreAPIYARPCClientParams defines the input
// for NewFxSemaphoreAPIYARPCClient. It provides the
// paramaters to get a SemaphoreAPIYARPCClient in an
// Fx application.
type FxSemaphoreAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxSemaphoreAPIYARPCClientResult defines the output
// of NewFxSemaphoreAPIYARPCClient. It provides a
// SemaphoreAPIYARPCClient to an Fx application.
type FxSemaphoreAPIYARPCClientResult struct {
	fx.Out

	Client SemaphoreAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxSemaphoreAPIYARPCClient provides a SemaphoreAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  apiv1.NewFxSemaphoreAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxSemaphoreAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxSemaphoreAPIYARPCClientParams) FxSemaphoreAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxSemaphoreAPIYARPCClientResult{
			Client: newSemaphoreAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxSemaphoreAPIYARPCProceduresParams defines the input
// for NewFxSemaphoreAPIYARPCProcedures. It provides the
// paramaters to get SemaphoreAPIYARPCServer procedures in an
// Fx application.
type FxSemaphoreAPIYARPCProceduresParams struct {
	fx.In

	Server      SemaphoreAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxSemaphoreAPIYARPCProceduresResult defines the output
// of NewFxSemaphoreAPIYARPCProcedures. It provides
// SemaphoreAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxSemaphoreAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxSemaphoreAPIYARPCProcedures provides SemaphoreAPIYARPCServer procedures to an Fx application.
// It expects a SemaphoreAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  apiv1.NewFxSemaphoreAPIYARPCProcedures(),
//	  ...
//	)
func NewFxSemaphoreAPIYARPCProcedures() interface{} {
	return func(params FxSemaphoreAPIYARPCProceduresParams) FxSemaphoreAPIYARPCProceduresResult {
		return FxSemaphoreAPIYARPCProceduresResult{
			Procedures: buildSemaphoreAPIYARPCProcedures(buildSemaphoreAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: SemaphoreAPIReflectionMeta,
		}
	}
}

// SemaphoreAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var SemaphoreAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.api.v1.SemaphoreAPI",
	FileDescriptors: yarpcFileDescriptorClosure60f52eba354a86a4,
}

type _SemaphoreAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_SemaphoreAPIYARPCCaller) CreateSemaphore(ctx context.Context, request *CreateSemaphoreRequest, options ...yarpc.CallOption) (*CreateSemaphoreResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "CreateSemaphore", request, newSemaphoreAPIServiceCreateSemaphoreYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*CreateSemaphoreResponse)
	if !ok {
		return nil, protobuf.CastError(emptySemaphoreAPIServiceCreateSemaphoreYARPCResponse, responseMessage)
	}
	return response, err
}

type _SemaphoreAPIYARPCHandler struct {
	server SemaphoreAPIYARPCServer
}

func (h *_SemaphoreAPIYARPCHandler) CreateSemaphore(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *CreateSemaphoreRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*CreateSemaphoreRequest)
		if !ok {
			return nil, protobuf.CastError(emptySemaphoreAPIServiceCreateSemaphoreYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.CreateSemaphore(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newSemaphoreAPIServiceCreateSemaphoreYARPCRequest() proto.Message {
	return &CreateSemaphoreRequest{}
}

func newSemaphoreAPIServiceCreateSemaphoreYARPCResponse() proto.Message {
	return &CreateSemaphoreResponse{}
}

var (
	emptySemaphoreAPIServiceCreateSemaphoreYARPCRequest  = &CreateSemaphoreRequest{}
	emptySemaphoreAPIServiceCreateSemaphoreYARPCResponse = &CreateSemaphoreResponse{}
)

var yarpcFileDescriptorClosure60f52eba354a86a4 = [][]byte{
	// uber/cadence/api/v1/service_semaphore.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x3b, 0x4f, 0xf3, 0x30,
		0x14, 0x55, 0xbe, 0xaf, 0x54, 0xea, 0x2d, 0x0f, 0xc9, 0x88, 0xb6, 0xea, 0x00, 0x55, 0x11, 0x52,
		0xa5, 0x82, 0xad, 0x94, 0x11, 0x16, 0xca, 0xc4, 0x82, 0xaa, 0x76, 0x40, 0x62, 0x89, 0x1c, 0xe7,
		0xaa, 0xb5, 0xa8, 0x63, 0x13, 0x27, 0x19, 0x2a, 0x7e, 0x02, 0x3f, 0x1a, 0xd5, 0x09, 0x29, 0x8f,
		0x0c, 0x6c, 0xf6, 0x79, 0xdc, 0x7b, 0xec, 0x03, 0xe3, 0x2c, 0xc4, 0x84, 0x09, 0x1e, 0x61, 0x2c,
		0x90, 0x71, 0x23, 0x59, 0xee, 0x33, 0x8b, 0x49, 0x2e, 0x05, 0x06, 0x16, 0x15, 0x37, 0x2b, 0x9d,
		0x20, 0x35, 0x89, 0x4e, 0x35, 0x39, 0xde, 0x8a, 0x69, 0x29, 0xa6, 0xdc, 0x48, 0x9a, 0xfb, 0xfd,
		0xf3, 0xfa, 0x09, 0xdf, 0x9c, 0xc3, 0x77, 0x0f, 0x3a, 0xf7, 0x09, 0xf2, 0x14, 0x17, 0x9f, 0xcc,
		0x1c, 0x5f, 0x33, 0xb4, 0x29, 0xe9, 0x40, 0x33, 0xd2, 0x8a, 0xcb, 0xb8, 0xe7, 0x0d, 0xbc, 0x51,
		0x6b, 0x5e, 0xde, 0xc8, 0x05, 0x1c, 0x56, 0x53, 0x82, 0x98, 0x2b, 0xec, 0xfd, 0x73, 0xfc, 0x41,
		0x85, 0x3e, 0x72, 0x85, 0x84, 0x40, 0xc3, 0xca, 0x0d, 0xf6, 0xfe, 0x0f, 0xbc, 0xd1, 0xde, 0xdc,
		0x9d, 0xc9, 0x19, 0xb4, 0xc3, 0x4c, 0xbc, 0x60, 0x1a, 0x38, 0xaa, 0xe1, 0x28, 0x28, 0xa0, 0x85,
		0xdc, 0xe0, 0xf0, 0x09, 0xba, 0xbf, 0xd2, 0x58, 0xa3, 0x63, 0x8b, 0xe4, 0x16, 0x5a, 0xd5, 0x02,
		0x97, 0xa8, 0x3d, 0x39, 0xa5, 0x35, 0xef, 0xa6, 0x3b, 0xeb, 0xce, 0x30, 0x79, 0x83, 0xfd, 0x0a,
		0xbf, 0x9b, 0x3d, 0x90, 0x35, 0x1c, 0xfd, 0x58, 0x44, 0xc6, 0xb5, 0xd3, 0xea, 0x3f, 0xa7, 0x7f,
		0xf9, 0x37, 0x71, 0x91, 0x7d, 0x8a, 0xd0, 0x15, 0x5a, 0xd5, 0x59, 0xa6, 0x27, 0x95, 0x7a, 0x51,
		0x94, 0x3b, 0xdb, 0xf6, 0x32, 0xf3, 0x9e, 0xfd, 0xa5, 0x4c, 0x57, 0x59, 0x48, 0x85, 0x56, 0xec,
		0x6b, 0x93, 0x57, 0x32, 0x5a, 0xb3, 0xa5, 0x66, 0xae, 0xbf, 0xb2, 0xd6, 0x1b, 0x6e, 0x64, 0xee,
		0x87, 0x4d, 0x87, 0x5d, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0x24, 0xa3, 0xdf, 0x06, 0x3c, 0x02,
		0x00, 0x00,
	},
	// uber/cadence/api/v1/semaphore.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x4d, 0x4a, 0x2d,
		0xd2, 0x4f, 0x4e, 0x4c, 0x49, 0xcd, 0x4b, 0x4e, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x33, 0xd4,
		0x2f, 0x4e, 0xcd, 0x4d, 0x2c, 0xc8, 0xc8, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
		0x12, 0x06, 0x29, 0xd2, 0x83, 0x2a, 0xd2, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0x54, 0x4a, 0xe7,
		0xe2, 0x0c, 0x86, 0xa9, 0x13, 0x52, 0xe5, 0xe2, 0x83, 0x6b, 0x8a, 0xcf, 0x4b, 0xcc, 0x4d, 0x95,
		0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x85, 0x8b, 0xfa, 0x25, 0xe6, 0xa6, 0x0a, 0x09, 0x71,
		0xb1, 0x14, 0x67, 0x56, 0xa5, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42, 0xf2,
		0x5c, 0xdc, 0x49, 0xa5, 0xc9, 0xd9, 0xa9, 0x25, 0xf1, 0x60, 0x29, 0x66, 0xb0, 0x14, 0x17, 0x44,
		0x28, 0x38, 0xb3, 0x2a, 0xd5, 0x29, 0x8e, 0x4b, 0x3c, 0x39, 0x3f, 0x57, 0x0f, 0x8b, 0x1b, 0x9c,
		0xf8, 0xe0, 0x2e, 0x08, 0x00, 0x39, 0x34, 0x80, 0x31, 0xca, 0x30, 0x3d, 0xb3, 0x24, 0xa3, 0x34,
		0x49, 0x2f, 0x39, 0x3f, 0x57, 0x1f, 0xd9, 0x6b, 0xba, 0x99, 0x29, 0x39, 0xfa, 0xe9, 0xf9, 0xfa,
		0x60, 0x0f, 0x41, 0xfd, 0x69, 0x9d, 0x58, 0x90, 0x59, 0x66, 0x98, 0xc4, 0x06, 0x16, 0x33, 0x06,
		0x04, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xfb, 0x02, 0x7f, 0x0b, 0x01, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) SemaphoreAPIYARPCClient {
			return NewSemaphoreAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
